extends:
  - qwen2.5_base.yaml

tokenizer_type: HuggingFaceTokenizer
tokenizer_model: Qwen/Qwen3-0.6B

# Qwen 3 0.6B
hidden_size: 1024
ffn_hidden_size: 3072
num_layers: 28
num_attention_heads: 16
num_query_groups: 8
kv_channels: 128
qk_layernorm: true
vocab_size: 151936
